//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVWS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", ConfigurationName="NAVWS.PortalIntegration_Port")]
    public interface PortalIntegration_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (InsertSeminarData_Result) of message InsertSeminarData_Result does not match the default value (InsertSeminarData)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration:InsertSeminarData", ReplyAction="*")]
        NAVWS.InsertSeminarData_Result InsertSeminarData(NAVWS.InsertSeminarData request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration:InsertSeminarData", ReplyAction="*")]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> InsertSeminarDataAsync(NAVWS.InsertSeminarData request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarData", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", IsWrapped=true)]
    public partial class InsertSeminarData
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", Order=0)]
        public string docNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", Order=1)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", Order=2)]
        public string searchName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", Order=3)]
        public int seminarDuration;
        
        public InsertSeminarData()
        {
        }
        
        public InsertSeminarData(string docNo, string name, string searchName, int seminarDuration)
        {
            this.docNo = docNo;
            this.name = name;
            this.searchName = searchName;
            this.seminarDuration = seminarDuration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertSeminarData_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/PortalIntegration", IsWrapped=true)]
    public partial class InsertSeminarData_Result
    {
        
        public InsertSeminarData_Result()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PortalIntegration_PortChannel : NAVWS.PortalIntegration_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PortalIntegration_PortClient : System.ServiceModel.ClientBase<NAVWS.PortalIntegration_Port>, NAVWS.PortalIntegration_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PortalIntegration_PortClient() : 
                base(PortalIntegration_PortClient.GetDefaultBinding(), PortalIntegration_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PortalIntegration_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalIntegration_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(PortalIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), PortalIntegration_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalIntegration_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PortalIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalIntegration_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PortalIntegration_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PortalIntegration_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NAVWS.InsertSeminarData_Result NAVWS.PortalIntegration_Port.InsertSeminarData(NAVWS.InsertSeminarData request)
        {
            return base.Channel.InsertSeminarData(request);
        }
        
        public void InsertSeminarData(string docNo, string name, string searchName, int seminarDuration)
        {
            NAVWS.InsertSeminarData inValue = new NAVWS.InsertSeminarData();
            inValue.docNo = docNo;
            inValue.name = name;
            inValue.searchName = searchName;
            inValue.seminarDuration = seminarDuration;
            NAVWS.InsertSeminarData_Result retVal = ((NAVWS.PortalIntegration_Port)(this)).InsertSeminarData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> NAVWS.PortalIntegration_Port.InsertSeminarDataAsync(NAVWS.InsertSeminarData request)
        {
            return base.Channel.InsertSeminarDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVWS.InsertSeminarData_Result> InsertSeminarDataAsync(string docNo, string name, string searchName, int seminarDuration)
        {
            NAVWS.InsertSeminarData inValue = new NAVWS.InsertSeminarData();
            inValue.docNo = docNo;
            inValue.name = name;
            inValue.searchName = searchName;
            inValue.seminarDuration = seminarDuration;
            return ((NAVWS.PortalIntegration_Port)(this)).InsertSeminarDataAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalIntegration_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PortalIntegration_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://grc-dkt-002.greencom.co.ke:7047/BC240/WS/CRONUS International Ltd./Codeuni" +
                        "t/PortalIntegration");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PortalIntegration_PortClient.GetBindingForEndpoint(EndpointConfiguration.PortalIntegration_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PortalIntegration_PortClient.GetEndpointAddress(EndpointConfiguration.PortalIntegration_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            PortalIntegration_Port,
        }
    }
}
